[package]
name = "todo"
description = "todo.txt terminal frontend"
version = "0.1.0"
rust-version = "1.81"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
fzf-wrapped = { workspace = true }
log = { workspace = true }
notify = { workspace = true }
simple_logger = { workspace = true }
tasks = { path = "../tasks" }
wait-timeout = { workspace = true }

[lints]
workspace = true
