[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dialoguer = { workspace = true }
fzf-wrapped = { workspace = true }
log = { workspace = true }
nix = { workspace = true }
simple_logger = { workspace = true }
tasks = { path = "../tasks" }
wait-timeout = { workspace = true }
